apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 10000 # เริ่มต้น 1 ตัว
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend-container
        image: moondev06/shoe-backend:v4
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URI
          value: "mongodb://mongo-service:27017/shoes_db"
        resources:
          requests:
            cpu: "100m" # จอง CPU ไว้เล็กน้อย
          limits:
            cpu: "200m" # จำกัดไว้ไม่ให้เกินนี้ เพื่อให้ HPA วัดผลได้
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000